onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - sharp
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  defu@<=6.1.4: '>=6.1.5'
  h3@<1.15.9: '>=1.15.9'
  h3@<=1.15.8: '>=1.15.9'
  hono@<4.12.12: '>=4.12.12'
  hono@<4.12.14: '>=4.12.14'
  hono@>=4.0.0 <=4.12.11: '>=4.12.12'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  smol-toml@<1.6.1: '>=1.6.1'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
