overrides:
  svgo: '>=4.0.2'
  brace-expansion: '>=5.0.7'
  hono: '>=4.12.27'
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
minimumReleaseAgeExclude:
  - '@loom-dev/layout@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0'
  - '@loom-dev/preview@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0'
  - '@loom-dev/react@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0'
  - '@loom-dev/renderer@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0'
  - '@loom-dev/runtime@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0'
  - '@loom-dev/scene@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0'
  - loom-dev@0.2.0 || 0.2.1 || 0.3.0 || 0.6.1 || 0.6.4 || 0.7.0
  - '@vela-rbxts/compiler-darwin-arm64@0.4.0 || 0.4.1'
  - '@vela-rbxts/compiler-darwin-x64@0.4.0 || 0.4.1'
  - '@vela-rbxts/compiler-linux-arm64-gnu@0.4.0 || 0.4.1'
  - '@vela-rbxts/compiler-linux-x64-gnu@0.4.0 || 0.4.1'
  - '@vela-rbxts/compiler-linux-x64-musl@0.4.0 || 0.4.1'
  - '@vela-rbxts/compiler-win32-x64-msvc@0.4.0 || 0.4.1'
  - '@vela-rbxts/compiler-wasm@0.4.1'
  - '@vela-rbxts/compiler@0.4.0 || 0.4.1'
  - '@vela-rbxts/config@0.4.0 || 0.4.1'
  - '@vela-rbxts/types@0.4.0 || 0.4.1'
